var ccb_resources = [
    {type:'image', src:"ccbResources/ccbDefaultImages.png"},
    {type:'image', src:"ccbResources/ccbParticleSmoke.png"},
    {type:'image', src:"playButton.png"},
    {type:'image', src:"parts_coin.png"},
    {type:'ccbi', src:"MainGameScene.ccbi"},
    {type:'image', src:"ccbResources/ccbParticleFire.png"},
    {type:'image', src:"parts_record.png"},
    {type:'image', src:"clickme.png"},
    {type:'image', src:"parts_bomb.png"},
    {type:'ccbi', src:"MainGameLayer.ccbi"},
    {type:'image', src:"ccbResources/ccbParticleStars.png"},
    {type:'image', src:"parts_player.png"},
    {type:'image', src:"clickme-down.png"},
    {type:'plist', src:"ccbResources/ccbDefaultImages.plist"},
    {type:'image', src:"ccbResources/ccbParticleSnow.png"},
];
